services:
  - type: web
    name: technical-trading-bot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    plan: free
    envVars:
      - key: PORT
        value: 8080
      - key: TELEGRAM_TOKEN
        value: "8686769653:AAH_E703LLE-rpV6mpOZh7ifd9_UpH85pb0"
      - key: TELEGRAM_CHAT_ID
        value: "8701685996"
      - key: FINNHUB_API_KEY
        value: "D8sh4dpr01qq7apvl2egd8sh4dpr01qq7apvl2f0" 
      - key: RENDER_DEPLOY_WEBHOOK
        value: "https://api.render.com/deploy/srv-d8slig6gvqtc738d9rjg?key=oAz0lVAFCyc"
